defaults: &defaults
  additional_info: true
  contact_phone: true
  description: true
  electricity: true
  light: true
  fire: true
  noise: true
  nature: true
  moop: true
  plan: true
  cocreation: true
  neighbors: true
  budgetplan: true
  seeking_members: true
  granting: false
  user_authentication_codes: false
  add_to_list: true
  granting_active: false
  footer_text: false
  footer_logo: false
  creation_sidebar_welcome: true

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
